---
- yum:
    name: lsyncd,libxml2-devel,lua-devel,lua-static,rsync
    state: present

- template:
    src: amzn.lsyncd.conf.j2
    dest: /etc/lsyncd.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart_lsyncd_service

- service:
    name: lsyncd
    state: started
    enabled: yes
