---
- import_tasks: amzn.yaml
  when:
    - ansible_distribution == "Amazon"

- import_tasks: centos7.yaml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
