---
- yum:
    name: rsync,xinetd
    state: present

- template:
    src: centos7.rsyncd.conf.j2
    dest: /etc/rsyncd.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart_xinetd_systemd

- template:
    src: centos7.rsync.j2
    dest: /etc/xinetd.d/rsync
    owner: root
    group: root
    mode: 0644
  notify:
    - restart_xinetd_systemd

- systemd:
    name: xinetd
    state: started
    enabled: yes
